### ISSUE TITLE
[0x0f013087: !unknown instruction!] when fusesoc run --target=sim barvinn

### ISSUE THREAD

**Issue by YI-MAX-YAN** [hossein1387/BARVINN#25]
Hello, thank you for maintaining this project. I met this 'Fail', and I don't know how to fix it. It seems like I use the wrong riscv core to gen code.
```
[ INFO] 1709600.00 ns Test Fail [0x0f013087: !unknown instruction!] Unknown Instruction, pc=200cc8 
[ INFO] 1710400.00 ns Test Fail [0x0e813107: !unknown instruction!] Unknown Instruction, pc=200ccc 
[ INFO] 1711200.00 ns Test Fail [0x0e013187: !unknown instruction!] Unknown Instruction, pc=200cd0 
[ INFO] 1712000.00 ns Test Fail [0x0d813207: !unknown instruction!] Unknown Instruction, pc=200cd4 
[ INFO] 1712800.00 ns Test Fail [0x0d013287: !unknown instruction!] Unknown Instruction, pc=200cd8 
[ INFO] 1713600.00 ns Test Fail [0x0c813307: !unknown instruction!] Unknown Instruction, pc=200cdc 
```
This is my Makefile in conv, I change the march.
`LDFLAGS = -nostdlib  -T$(ROOT_DIR)/common/link.ld -Map=$(OUT_DIR)/$(PROJ).map`
` CCFLAGS = -march=rv32imafd -std=gnu99 -ffast-math -fno-builtin-printf`

**Comment by hossein1387** [comment]
Hi Thanks for your interest in BARVINN!
Unfortunately  BARVINN does not support `rv32imafd`. We only support `rv32i`.  That is probably why you are getting this error.

**Comment by YI-MAX-YAN** [comment]
Thank you so much for your help! I wanted to let you know that I have successfully resolved the issue and everything is working perfectly now. I truly appreciate your quick response and support in fixing the problem. Your expertise and guidance have been invaluable. Thanks again!
