### ISSUE TITLE
Can't find /csrc/conv/common/crt0.S

### ISSUE THREAD

**Issue by 33xsk** [hossein1387/BARVINN#30]
Excuse me, is /csrc/conv/common damaged ?

**Comment by hossein1387** [comment]
it should have point to the pito_riscv common directory. It is now fixed.

**Comment by shenbai12138** [comment]
/home/tao/BARVINN/csrc/conv/src//main.c: In function 'main_thread':
/home/tao/BARVINN/csrc/conv/src//main.c:41:22: error: 'DMA_START_ADDR' undeclared (first use in this function)
     int wbase_addr = DMA_START_ADDR;
                      ^~~~~~~~~~~~~~
/home/tao/BARVINN/csrc/conv/src//main.c:41:22: note: each undeclared identifier is reported only once for each function it appears in
Excuse me, how can I get  int wbase_addr = DMA_START_ADDR, : each undeclared identifier is reported only once for each function it appears in

**Comment by 33xsk** [comment]
Is a header file missing?

**Comment by shenbai12138** [comment]
Is csrfile.mem lost?

**Comment by hossein1387** [comment]
@shenbai12138 The code you are using was part of my test code when I was developing DMA. Unfortunately the DMA is still work in progress. For now, you can only use local rams on MVUs to store data.
